[project]
name = "toy"
version = "0.1.0"
description = "A toy package with vector operations"
dependencies = ["numpy"]

[build-system]
requires = [
    "scikit-build-core",
    "meson",
    "numpy>=1.21",
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
sdist.exclude = [
    ".github",
    "**/*.pyf",
    "**/*.f90",
    "**/*.F",
]

[tool.cibuildwheel]
test-requires = "pytest"
test-command = "pytest"
before-all = "apt install -y libblas-dev gfortran"
select = "cp3{7,8,9,1?}-*"
