name: publish

on: workflow_dispatch

permissions:
  contents: read

jobs:
  linux-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install cibuildwheel
        run: |
          python -m pip install -U pip
          pip install cibuildwheel
      - name: Build Wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: x86_64
          CIBW_BUILD: "cp3{9,1?}-manylinux*"
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
      - name: Upload Wheels
        run: ./.github/workflows/upload_wheels.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
